
//var p = Professors.build({professor_name: "Kozai"})
//p.save()

//var d = Departments.build({department_name: "Math Science"})
//d.save()
//var c = Courses.build({name: "62C", number:11, name_and_number:"62C 11",professor_name:"Kozai", department_name:"Math Science", type: "LEC", title: "Datastructure", ccn: 5, units: 2.5, time: "MW", location: "WHEELER", final_slot: 5, limit: 10, enrolled: 5, waitlist: 0, note: ""})
//c.save()
//var r = Reviews.build({rating_1:5, rating_2:3, rating_3:5, review:"Terrible", professor_name: "Denero"})
//r.save()
//var c = Sections.build({discussion: "11.185", type: "5", name_and_number:"62C 11", instructor: "END", ccn: 5, time:"MW", location: "as", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var s = Schedules.build({unique_id: "99.12333", name_and_number:"62C 11"})
//s.save()

//Schedules.findAll().then(function(courses){console.log(courses)})

//var c = Sections.build({professor_name:"McDavid",department_name:"Math Science",discussion: "11.185", type: "Lab", name_and_number:"110 11", instructor: "TA", ccn: 34344, time:"R 1630PM 1730PM", location: "EVANS", limit: 15, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Kashi",department_name:"Economics",discussion: "11.185", type: "Discussion", name_and_number:"140E 11", instructor: "TBD", ccn: 34345, time:"R 1600PM 1700PM", location: "EVANS", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"McDavid",department_name:"Math Science",discussion: "11.185", type: "Discussion", name_and_number:"110 11", instructor: "TA1", ccn: 51092, time:"MW 1000AM 1130AM", location: "EVANS", limit: 16, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"McDavid",department_name:"Math Science",discussion: "11.144", type: "Lab", name_and_number:"110 11", instructor: "TA3", ccn: 52412, time:"TR 1500PM 1700PM ", location: "CORY", limit: 10, enrolled: 10, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"McDavid",department_name:"Math Science",discussion: "11.190", type: "Discussion", name_and_number:"110 11", instructor: "TA4", ccn: 4214, time:"MW", location: "SODA", limit: 23, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"McDavid",department_name:"Math Science",discussion: "11.124", type: "Discussion", name_and_number:"110 11", instructor: "TA4", ccn: 4123, time:"R 1000AM 1130AM", location: "CORY", limit: 10, enrolled: 12, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Kashi",department_name:"Economics",discussion: "11.185", type: "Discussion", name_and_number:"140E 11", instructor: "TBDTATBA", ccn: 24, time:"T 1600PM 1700PM", location: "SODA", limit: 25, enrolled: 15, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Kashi",department_name:"Economics",discussion: "11.185", type: "Discussion", name_and_number:"140E 11", instructor: "Alex", ccn: 242, time:"W 1600PM 1700PM", location: "SODA", limit: 10, enrolled: 8, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Kashi",department_name:"Economics",discussion: "11.185", type: "Discussion", name_and_number:"140E 11", instructor: "Ryan", ccn: 1242, time:"T 1000AM 1130AM", location: "SODA", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Kashi",department_name:"Economics",discussion: "11.185", type: "Discussion", name_and_number:"140E 11", instructor: "Andy", ccn: 900, time:"T 1500PM 1700PM", location: "SODA", limit: 30, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Necula",department_name:"Biology",discussion: "11.185", type: "Lab", name_and_number:"121 11", instructor: "Shai", ccn: 12, time:"MW 1000AM 1130AM", location: "SODA", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Necula",department_name:"Biology",discussion: "11.185", type: "Lab", name_and_number:"121 11", instructor: "Shay", ccn: 55, time:"R 1600PM 1700PM", location: "SODA", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Necula",department_name:"Biology",discussion: "11.185", type: "Lab", name_and_number:"121 11", instructor: "TA", ccn: 123, time:"R 1600PM 1700PM", location: "SODA", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Necula",department_name:"Biology",discussion: "11.185", type: "Discussion", name_and_number:"121 11", instructor: "END", ccn: 434, time:"MW 1000AM 1130AM", location: "WHEELER", limit: 10, enrolled: 10, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Necula",department_name:"Biology",discussion: "11.185", type: "Discussion", name_and_number:"121 11", instructor: "END", ccn: 121, time:"MW", location: "GBC", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.185", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 434, time:"MW 1000AM 1100AM", location: "LI-KA-SHING", limit: 10, enrolled: 8, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.185", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 33, time:"R 1600PM 1700PM", location: "EVANS", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.185", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 2352, time:"W 1130AM 1230PM", location: "SODA", limit: 10, enrolled: 14, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.185", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 235, time:"MW 9OOOAM 1000AM", location: "SODA", limit: 15, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.185222", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 64, time:"R 1000AM 1200PM", location: "SODA", limit: 40, enrolled: 12, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Jay",department_name:"History",discussion: "11.18523", type: "Discussion", name_and_number:"62C 11", instructor: "END", ccn: 511, time:"MW 1000AM 1130AM", location: "SODA", limit: 60, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.1822", type: "Lab", name_and_number:"155 12", instructor: "END", ccn: 575, time:"F 1200PM 1400PM", location: "SODA", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.1898", type: "Lab", name_and_number:"155 12", instructor: "END", ccn: 586, time:"TR 1200PM 1300PM", location: "STADIUM", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.184", type: "Discussion", name_and_number:"155 12", instructor: "END", ccn: 90, time:"W 1300PM 1400PM", location: "EVANS", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.181", type: "Discussion", name_and_number:"155 12", instructor: "END", ccn: 23, time:"MW 9000AM 1000AM", location: "SODA", limit: 10, enrolled: 8, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.183", type: "Lab", name_and_number:"155 12", instructor: "END", ccn: 12, time:"MW 8000AM 1000AM", location: "STADIUM", limit: 10, enrolled: 5, waitlist: 10})
//c.save()
//var c = Sections.build({professor_name:"Garcia",department_name:"UGBA",discussion: "11.187", type: "Lab", name_and_number:"155 12", instructor: "END", ccn: 12412, time:"MW 8000AM 1030AM", location: "SODA", limit: 30, enrolled: 12, waitlist: 10})
//c.save()
//


//var c = Courses.build({name: "52", number:11, name_and_number:"52 11",professor_name:"Garcia", department_name:"Math Science", type: "LEC", title: "Data Structure", ccn: 5, units: 1, time: "T 1000AM 1130AM", location: "CORY", final_slot: 5, limit: 10, enrolled: 5, waitlist: 0, note: "This course if offered for the last time."})
//c.save()
//
//var c = Courses.build({name: "121", number:11, name_and_number:"121 11",professor_name:"Necula", department_name:"Biology", type: "LEC", title: "Cell Engineering", ccn: 89723, units: 7, time: "Th 1400PM 1600PM", location: "CORY", final_slot: 18, limit: 20, enrolled:15, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "64B", number:11, name_and_number:"64B 11",professor_name:"Garcia", department_name:"UGBA", type: "LEC", title: "How To Start a Business", ccn: 1092, units: 6, time: "W 1500PM 1630PM", location: "SODA", final_slot: 5, limit: 50, enrolled: 5, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "62C", number:11, name_and_number:"62C 11",professor_name:"Jay", department_name:"History", type: "LEC", title: "Data Structure", ccn: 22, units: 2, time: "MW 1200PM 1600PM", location: "WHEELER", final_slot: 3, limit: 10, enrolled: 5, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "EE20", number:14, name_and_number:"EE20 14",professor_name:"Babak", department_name:"Electrical Engineering", type: "LEC", title: "Systems and Signals", ccn: 87, units: 2.5, time: "MW 1700PM 1830PM", location: "WHEELER", final_slot: 5, limit: 10, enrolled: 5, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "155", number:12, name_and_number:"155 12",professor_name:"Garcia", department_name:"Math Science", type: "LEC", title: "Life of Pie", ccn: 4634, units: 2.5, time: "MW 1500PM 1700PM", location: "UGBA", final_slot: 7, limit: 30, enrolled: 5, waitlist: 0, note: "This course is for declared students only."})
//c.save()
//
//var c = Courses.build({name: "110", number:11, name_and_number:"110 11",professor_name:"McDavid", department_name:"Math Science", type: "LEC", title: "Becoming a Golden Bear", ccn: 34343, units: 2, time: "TTh 1100AM 1300PM", location: "WHEELER", final_slot: 6, limit: 10, enrolled: 5, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "24", number:11, name_and_number:"24 11",professor_name:"Ben-David", department_name:"Math Science", type: "SEMINAR", title: "The Real Life", ccn: 12312, units: 3, time: "MW 1000AM 1200PM", location: "WHEELER", final_slot: 1, limit: 40, enrolled: 31, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "18D", number:11, name_and_number:"18D 11",professor_name:"Lenovo", department_name:"Physics", type: "LEC", title: "Computer Electricity", ccn: 314, units: 4, time: "MF 9000AM 1300PM", location: "WHEELER", final_slot: 2, limit: 10, enrolled: 7, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "140E", number:11, name_and_number:"140E 11",professor_name:"Kashi", department_name:"Economics", type: "LEC", title: "Data Structure", ccn: 5643, units: 4, time: "RF 8000AM 9300AM", location: "LI-KA-SHING", final_slot: 5, limit: 20, enrolled: 20, waitlist: 0, note: ""})
//c.save()
//
//var c = Courses.build({name: "89Y", number:12, name_and_number:"89Y 12",professor_name:"Alex", department_name:"Political Science", type: "LEC", title: "Data Structure", ccn: 124, units: 5, time: "MW 1700PM 1900PM", location: "SOUTH HALL", final_slot: 5, limit: 10, enrolled: 9, waitlist: 0, note: ""})
//c.save()

//var p = Professors.build({professor_name: "Necula"})
//p.save()
//
//var p = Professors.build({professor_name: "Jay"})
//p.save()
//var p = Professors.build({professor_name: "Kashi"})
//p.save()
//var p = Professors.build({professor_name: "Babak"})
//p.save()
//var p = Professors.build({professor_name: "Alex"})
//p.save()
//var p = Professors.build({professor_name: "Garcia"})
//p.save()
//var p = Professors.build({professor_name: "Ben-David"})
//p.save()
//var p = Professors.build({professor_name: "Gupta"})
//p.save()
//var p = Professors.build({professor_name: "Lee"})
//p.save()
//var p = Professors.build({professor_name: "Benjamin Jones"})
//p.save()
//var p = Professors.build({professor_name: "McDavid"})
//p.save()
//var p = Professors.build({professor_name: "Lenovo"})
//p.save()

//var r = Reviews.build({rating_1:9, rating_2:10, rating_3:9, review:"This Professor... overall good experience", professor_name: "Necula"})
//r.save()
//
//var r = Reviews.build({rating_1:7, rating_2:7, rating_3:8, review:"I like the way he explains...great lectures. ", professor_name: "Kashi"})
//r.save()
//var r = Reviews.build({rating_1:10, rating_2:9, rating_3:4, review:"Great presentation.", professor_name: "Alex"})
//r.save()
//var r = Reviews.build({rating_1:7, rating_2:8, rating_3:9, review:"", professor_name: "Jay"})
//r.save()
//var r = Reviews.build({rating_1:5, rating_2:7, rating_3:7, review:"Not every Professor gets a review from me...", professor_name: "Ben-David"})
//r.save()
//var r = Reviews.build({rating_1:8, rating_2:8, rating_3:8, review:"I hope you'll read this review.. it will help you decide about the class", professor_name: "Ben-David"})
//r.save()
//var r = Reviews.build({rating_1:7, rating_2:7, rating_3:5, review:"Awesome", professor_name: "Garcia"})
//r.save()
//var r = Reviews.build({rating_1:10, rating_2:7, rating_3:8, review:"Perfect", professor_name: "Garcia"})
//r.save()
//var r = Reviews.build({rating_1:5, rating_2:3, rating_3:9, review:"Terrible", professor_name: "Garcia"})
//r.save()
//var r = Reviews.build({rating_1:8, rating_2:6, rating_3:9, review:"ahhh..I'm not sure what to say", professor_name: "Benjamin Jones"})
//r.save()
//var r = Reviews.build({rating_1:10, rating_2:10, rating_3:10, review:"Should retire already...", professor_name: "Lenovo"})
//r.save()
//var r = Reviews.build({rating_1:4, rating_2:5, rating_3:6, review:"I like the topic, but...", professor_name: "McDavid"})
//r.save()
